### ISSUE TITLE
Bug: nextCard

### ISSUE THREAD

**Issue by nicoHAW** [nicoHAW/BAI1-P1_AZ4#3]
Expected ->   CK,  C7, CT, C2, CQ, C5    (s)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "cards.Card.getSuit()" because "nextCard" is null
	at CXE_CardHand_Distr/cardHand.Hand.isSuited(Hand.java:111)
	at CXE_CardHand_Distr/cardHand.TestFrameAndStarter.main(TestFrameAndStarter.java:108)

**Comment by nicoHAW** [comment]
fixed -. was a problem with changing a while to a for loop. a i++ was still there causing trouble.
